// One-off generator for logic/src/india-border.ts. Not run in CI or on the request path.
//
// FIRMS area queries are bounding boxes, and the Punjab and Bihar boxes reach into
// Pakistan and Nepal. This clips India's border (Natural Earth 1:10m, India point of
// view, public domain) to each region box and writes the result as a TS constant so
// fetchHotspots can drop detections outside India with a plain ray cast.
//
// Run from the repo root:
//   curl -sSLo /tmp/ne_ind.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries_ind.geojson
//   node pipeline/india-border.mjs /tmp/ne_ind.geojson

import { readFileSync, writeFileSync } from 'node:fs';

const REGION_BBOX = {
  punjab: [73.8, 29.5, 76.95, 32.55],
  bihar: [83.3, 24.2, 88.3, 27.55],
  delhi: [76.8, 28.4, 77.4, 28.9],
  telangana: [77.2, 15.8, 81.85, 19.95],
};
const PAD = 0.2; // degrees; keeps clipped edges well outside anything FIRMS returns
const TOLERANCE = 0.001; // degrees, about 100 m; 0.005 misplaced a real fire 500 m from the border

const src = process.argv[2];
if (!src) throw new Error('usage: node pipeline/india-border.mjs <ne_10m_admin_0_countries_ind.geojson>');
const india = JSON.parse(readFileSync(src, 'utf8')).features.find((f) => f.properties.ADM0_A3 === 'IND');
if (!india) throw new Error('IND feature not found');
const polygons = india.geometry.type === 'Polygon' ? [india.geometry.coordinates] : india.geometry.coordinates;

// Sutherland-Hodgman against one axis-aligned edge.
function clipEdge(ring, inside, cross) {
  const out = [];
  for (let i = 0; i < ring.length; i++) {
    const cur = ring[i];
    const prev = ring[(i + ring.length - 1) % ring.length];
    if (inside(cur)) {
      if (!inside(prev)) out.push(cross(prev, cur));
      out.push(cur);
    } else if (inside(prev)) {
      out.push(cross(prev, cur));
    }
  }
  return out;
}
const atX = (x) => (a, b) => [x, a[1] + ((b[1] - a[1]) * (x - a[0])) / (b[0] - a[0])];
const atY = (y) => (a, b) => [a[0] + ((b[0] - a[0]) * (y - a[1])) / (b[1] - a[1]), y];

function clipRing(ring, [w, s, e, n]) {
  let r = ring.slice(0, -1); // GeoJSON rings repeat the first point
  r = clipEdge(r, (p) => p[0] >= w, atX(w));
  r = clipEdge(r, (p) => p[0] <= e, atX(e));
  r = clipEdge(r, (p) => p[1] >= s, atY(s));
  r = clipEdge(r, (p) => p[1] <= n, atY(n));
  return r;
}

// Douglas-Peucker on an open polyline.
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let maxD = 0;
  let idx = 0;
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const len = Math.hypot(dx, dy) || 1e-12;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + b[0] * a[1] - b[1] * a[0]) / len;
    if (d > maxD) [maxD, idx] = [d, i];
  }
  if (maxD <= tol) return [a, b];
  return [...simplify(pts.slice(0, idx + 1), tol).slice(0, -1), ...simplify(pts.slice(idx), tol)];
}

const out = {};
for (const [region, [w, s, e, n]] of Object.entries(REGION_BBOX)) {
  const box = [w - PAD, s - PAD, e + PAD, n + PAD];
  const rings = [];
  for (const polygon of polygons) {
    for (const ring of polygon) {
      const clipped = clipRing(ring, box);
      if (clipped.length < 3) continue;
      // Split the closed ring in two so Douglas-Peucker has distinct endpoints.
      const mid = Math.floor(clipped.length / 2);
      const simple = [
        ...simplify(clipped.slice(0, mid + 1), TOLERANCE).slice(0, -1),
        ...simplify([...clipped.slice(mid), clipped[0]], TOLERANCE).slice(0, -1),
      ];
      if (simple.length >= 3) rings.push(simple.map(([x, y]) => [+x.toFixed(4), +y.toFixed(4)]));
    }
  }
  out[region] = rings;
  console.log(`${region}: ${rings.length} ring(s), ${rings.reduce((t, r) => t + r.length, 0)} vertices`);
}

const ts = `// GENERATED by pipeline/india-border.mjs. Do not edit by hand; regenerate instead.
// Source: Natural Earth 1:10m admin-0 countries, India point of view (public domain),
// clipped to each REGION_BBOX padded by ${PAD} deg and simplified at ${TOLERANCE} deg.
import type { Region } from './types';

/** India's land border inside each region box: rings of [lon, lat], even-odd rule. */
export const INDIA_BORDER: Record<Region, ReadonlyArray<ReadonlyArray<readonly [number, number]>>> = ${JSON.stringify(out)};
`;
writeFileSync('logic/src/india-border.ts', ts);
console.log('wrote logic/src/india-border.ts');
