// One-off generator for frontend/src/towns.ts, the places the detail panel measures
// "About 12 km NE of <town>" from. Not run in CI or on the request path.
//
// Every Natural Earth 1:10m populated place (public domain) that falls inside India's
// states by frontend/public/boundaries/states.bin, so Gilgit and Muzaffarabad count,
// plus a hand-kept list of district towns in the stubble belt and Telangana / AP where
// Natural Earth is sparse.
//
//   curl -sSLo /tmp/ne_places.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_populated_places_simple.geojson
//   node pipeline/towns.mjs /tmp/ne_places.geojson

import { readFileSync, writeFileSync } from 'node:fs';

import { decodeStateGrid } from '../logic/src/geo.ts';

const src = process.argv[2];
if (!src) throw new Error('usage: node pipeline/towns.mjs <ne_10m_populated_places_simple.geojson>');

const bin = readFileSync(new URL('../frontend/public/boundaries/states.bin', import.meta.url));
const stateAt = decodeStateGrid(bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength));

// [name, lat, lon]: district towns kept from the four-region list.
const DISTRICT_TOWNS = [
  ['Amritsar', 31.634, 74.872], ['Ludhiana', 30.901, 75.857], ['Jalandhar', 31.326, 75.576],
  ['Patiala', 30.34, 76.386], ['Bathinda', 30.211, 74.945], ['Firozpur', 30.925, 74.613],
  ['Sangrur', 30.245, 75.844], ['Moga', 30.817, 75.174], ['Gurdaspur', 32.041, 75.405],
  ['Hoshiarpur', 31.532, 75.912],
  ['Patna', 25.594, 85.137], ['Gaya', 24.796, 85.008], ['Bhagalpur', 25.244, 86.972],
  ['Muzaffarpur', 26.12, 85.39], ['Darbhanga', 26.152, 85.897], ['Purnia', 25.778, 87.475],
  ['Ara', 25.556, 84.663], ['Begusarai', 25.418, 86.133], ['Chhapra', 25.78, 84.747],
  ['Motihari', 26.648, 84.917], ['Sasaram', 24.953, 84.031],
  ['New Delhi', 28.614, 77.209], ['Narela', 28.853, 77.093], ['Najafgarh', 28.609, 76.98],
  ['Gurugram', 28.459, 77.027], ['Noida', 28.535, 77.391], ['Ghaziabad', 28.669, 77.454],
  ['Faridabad', 28.408, 77.317],
  ['Hyderabad', 17.385, 78.487], ['Warangal', 17.969, 79.594], ['Karimnagar', 18.438, 79.129],
  ['Nizamabad', 18.672, 78.094], ['Khammam', 17.247, 80.151], ['Adilabad', 19.664, 78.532],
  ['Mahabubnagar', 16.737, 77.988], ['Nalgonda', 17.058, 79.267], ['Mancherial', 18.873, 79.463],
  ['Kothagudem', 17.551, 80.619], ['Bhadrachalam', 17.669, 80.893],
];

const towns = new Map(DISTRICT_TOWNS.map(([name, lat, lon]) => [name, [name, lat, lon]]));
let fromNe = 0;
for (const f of JSON.parse(readFileSync(src, 'utf8')).features) {
  const { name, latitude: lat, longitude: lon } = f.properties;
  if (!stateAt(lon, lat) || towns.has(name)) continue;
  // Drop places within 3 km of one already kept (Natural Earth lists some twice).
  if ([...towns.values()].some(([, a, b]) => Math.abs(a - lat) < 0.03 && Math.abs(b - lon) < 0.03)) continue;
  towns.set(name, [name, Math.round(lat * 1000) / 1000, Math.round(lon * 1000) / 1000]);
  fromNe++;
}

const rows = [...towns.values()].sort((a, b) => a[0].localeCompare(b[0]));
const body = rows.map(([n, a, b]) => `  [${JSON.stringify(n)}, ${a}, ${b}],`).join('\n');
writeFileSync(
  new URL('../frontend/src/towns.ts', import.meta.url),
  `// GENERATED by pipeline/towns.mjs. Do not edit by hand; regenerate instead.\n` +
    `// Natural Earth 1:10m populated places inside India's states, plus district towns.\n` +
    `/** [name, lat, lon] */\n` +
    `export const TOWNS: ReadonlyArray<readonly [string, number, number]> = [\n${body}\n];\n`,
);
console.log(`wrote frontend/src/towns.ts: ${rows.length} places (${fromNe} from Natural Earth)`);
for (const want of ['Gilgit', 'Leh', 'Port Blair', 'Itanagar', 'Chennai']) {
  if (!towns.has(want)) throw new Error(`${want} missing`);
}
console.log('ok  Gilgit, Leh, Port Blair, Itanagar, Chennai present');
